Updated to Python 3 and Pycryptodome
0x0L/rs-utils pull request #2
Opened 2018-07-30 13:21 UTC by tj-murphy

I updated all the code to Python 3 and also changed all the crypto routines to use pycryptodome instead of the deprecated pycrypto.

This is my first time doing anything on git, so if anything is wrong here, please let me know! I would love to have any of my procedural errors corrected. Thanks!

2018-07-30 14:00 UTC, 0x0L commented on bin/psarc.py
> +    return bytes(data + bytearray(padding))
Why not 'data + bytes(padding)'  ?

2018-07-30 14:04 UTC, 0x0L commented on bin/psarc.py
>      return output + 56 * chr(0)
This won't work

2018-07-30 14:04 UTC, 0x0L commented on bin/psarc.py
>      return output + 56 * chr(0)
This need to be changed

2018-07-30 14:08 UTC, 0x0L requested changes
Hi,

Thanks for your PR. I'm willing to merge this if you address the following issues:
1. fix the unecessary bytearray (we usually don't mutate anything so bytes is enough)
2. maintain python 2.7 compat

2018-07-30 14:08 UTC, 0x0L commented on bin/psarc.py
>      t += 56 * chr(0)
Same here

2018-07-30 14:08 UTC, 0x0L commented on bin/psarc.py
> +    ivector = bytearray(16)
`bytes(...)`

2018-07-30 14:08 UTC, 0x0L commented on bin/psarc.py
> +    data = bytearray()
`bytes()`

2018-07-31 16:52 UTC, tj-murphy commented
Hi,

I went through and changed every bytearray to bytes. I also found a few chr(0)'s that I had missed earlier on, which have now been changed over. Not sure what your issue was with the spots where you said "This needs to be changed" or "same here" so I haven't made any changes yet.

Also not sure how I'm supposed to maintain Python 2.7 compatibility when the syntaxes are fundamentally different between the versions, particularly with how print statements work. If you could say where the issues are that would be great, or if it's not worth your time, feel free to just say "I don't want this PR".

Thanks!

2018-07-31 17:55 UTC, 0x0L commented
There are several ways to maintain compatibility with python 2.7 (see http://python-future.org/compatible_idioms.html). For the print function it's really easy. The other possible source of problem here would be the confusion between bytes and str.

2018-08-01 14:21 UTC, tj-murphy commented
After a bit of research, I've gotten things running in both Python 2 and Python 3 environments. I also removed all instances of bytearray. I believe that handles the issues raised?

Please let me know if you'd like any further changes made.

2018-08-09 19:45 UTC, 0x0L commented
Thanks, looks good.
Could you please squash all the commits before I merge ? Thanks

2018-08-13 18:37 UTC, tj-murphy commented
Okay, I think I squashed commits. This is the first time I've done that so may have done something wrong but I think it worked; please let me know if not. Thanks!

2018-08-13 18:50 UTC, 0x0L approved these changes

2018-08-13 18:50 UTC, merged

2018-08-13 18:51 UTC, 0x0L commented
Thanks for the PR